#!/bin/bash

if [ "$1" == "" ];
then
    echo "Usage: $0 <commit-id>"
    exit 1
fi

case "$1" in 
    release)
        COMMIT_ID=$(git release-commit)
        ;;
    *)
        COMMIT_ID="$1"
        ;;
esac
    
for issue in $(git issues "$COMMIT_ID"..); do
    subject=$(curl -s -u"$user_auth" \
            'http://bugtracking.wkd.wolterskluwer.de/rest/api/latest/issue/'$issue|\
            grep -o -P '"summary":"(.*?)",'|head -1|\
            sed 's/"summary":"//g'|sed 's/[\]//g'i|sed 's/",$//g')
    p_status=$(curl -s -u"$user_auth" \
            'http://bugtracking.wkd.wolterskluwer.de/rest/api/latest/issue/'$issue|\
            grep -o -P '"name":"(.*?)",'|tail -1|\
            sed 's/"name":"//g'|sed 's/[\]//g'i|sed 's/",$//g')                  

    printf '[%s] %s: %s\n' "$p_status" "$issue" "$subject"
done;
