#!/bin/bash

cwd=$(pwd)
for dir in $(find . -type d -name ".git");
do
	cd "$cwd/${dir%/.git}"
	uncommitted_changes=$(git status --porcelain|wc -l)
	if [ "$uncommitted_changes" != "0" ];
	then
		echo "$(pwd): $uncommitted_changes files changed"
	fi
done
cd "$cwd"
